// Code generated by MockGen. DO NOT EDIT.
// Source: abstract.go
//
// Generated by this command:
//
//	mockgen -source=abstract.go -destination=notificator_mock.go -package=notifier
//

// Package notifier is a generated GoMock package.
package notifier

import (
	reflect "reflect"
	entities "tcp_proxy/internal/entities"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificator is a mock of Notificator interface.
type MockNotificator struct {
	ctrl     *gomock.Controller
	recorder *MockNotificatorMockRecorder
}

// MockNotificatorMockRecorder is the mock recorder for MockNotificator.
type MockNotificatorMockRecorder struct {
	mock *MockNotificator
}

// NewMockNotificator creates a new mock instance.
func NewMockNotificator(ctrl *gomock.Controller) *MockNotificator {
	mock := &MockNotificator{ctrl: ctrl}
	mock.recorder = &MockNotificatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificator) EXPECT() *MockNotificatorMockRecorder {
	return m.recorder
}

// SendInfoMessage mocks base method.
func (m *MockNotificator) SendInfoMessage(message string, args ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendInfoMessage", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInfoMessage indicates an expected call of SendInfoMessage.
func (mr *MockNotificatorMockRecorder) SendInfoMessage(message any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInfoMessage", reflect.TypeOf((*MockNotificator)(nil).SendInfoMessage), varargs...)
}

// SendInfoNewGRPCRequest mocks base method.
func (m *MockNotificator) SendInfoNewGRPCRequest(remoteIP, destination string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInfoNewGRPCRequest", remoteIP, destination)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInfoNewGRPCRequest indicates an expected call of SendInfoNewGRPCRequest.
func (mr *MockNotificatorMockRecorder) SendInfoNewGRPCRequest(remoteIP, destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInfoNewGRPCRequest", reflect.TypeOf((*MockNotificator)(nil).SendInfoNewGRPCRequest), remoteIP, destination)
}

// SendInfoNewRequest mocks base method.
func (m *MockNotificator) SendInfoNewRequest(n *entities.Notification, destination string, counts int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInfoNewRequest", n, destination, counts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInfoNewRequest indicates an expected call of SendInfoNewRequest.
func (mr *MockNotificatorMockRecorder) SendInfoNewRequest(n, destination, counts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInfoNewRequest", reflect.TypeOf((*MockNotificator)(nil).SendInfoNewRequest), n, destination, counts)
}

// SendTaskErrMessage mocks base method.
func (m *MockNotificator) SendTaskErrMessage(service string, startedAt, finishedAt time.Time, message string, errs ...Object) error {
	m.ctrl.T.Helper()
	varargs := []any{service, startedAt, finishedAt, message}
	for _, a := range errs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendTaskErrMessage", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTaskErrMessage indicates an expected call of SendTaskErrMessage.
func (mr *MockNotificatorMockRecorder) SendTaskErrMessage(service, startedAt, finishedAt, message any, errs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{service, startedAt, finishedAt, message}, errs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTaskErrMessage", reflect.TypeOf((*MockNotificator)(nil).SendTaskErrMessage), varargs...)
}
